# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name 
print("Islam")

Islam

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
dataInfo = pd.read_csv('../data/listings.csv')

#print first 5 rowa from the csv file
dataInfo.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [4]:
# 1. How many listings are there with a price less than 100? 
price = len(dataInfo[dataInfo["price"] < 100])
desiredPrice = f"listings with price under 100: {price}"
print(desiredPrice)

listings with price under 100: 22778

In [5]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk = dataInfo[dataInfo["neighbourhood_group"] == "Brooklyn"]
df_bkFiltered = len(df_bk)
update = f"Number of listings in Brooklyn: {df_bkFiltered}"
print(update)

Number of listings in Brooklyn: 18632

In [8]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
priceFilter_bk = len(df_bk[df_bk["price"] < 100])
priceBK = f"Number of listings in Brooklyn with a price less than 100: {priceFilter_bk}"
print(priceBK)

Number of listings in Brooklyn with a price less than 100: 10473

In [12]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
hostName = dataInfo[dataInfo["host_name"].isin(["Micheal", "David", "John", "Daniel"])]
hostFilter = len(hostName)
hostTotal = f"Total records with the host names of Michael, David, John and Daniel: {hostFilter}"
print(hostTotal)

Total records with the host names of Michael, David, John and Daniel: 874

In [13]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
dataInfo["adjusted_price"] = np.where(dataInfo["neighbourhood"] == "Williamsburg", dataInfo["price"] + 100, dataInfo["price"])
dataInfo[["neighbourhood", "price", "adjusted_price"]].head(20)

         neighbourhood  price  adjusted_price
0              Midtown    175             175
1         Clinton Hill     75              75
2   Bedford-Stuyvesant     60              60
3          Sunset Park    175             175
4       Hell's Kitchen     65              65
5      Upper West Side     75              75
6            Chinatown    140             140
7         West Village    160             160
8          South Slope     88              88
9      Upper West Side     85              85
10        West Village     65              65
11        Williamsburg    109             209
12         East Harlem    239             239
13         Fort Greene    182             182
14         East Harlem     96              96
15        Williamsburg    299             399
16  Bedford-Stuyvesant    120             120
17     Windsor Terrace    135             135
18              Inwood     86              86
19        East Village    220             220

In [14]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
roomTotal = len(dataInfo)
privateTotal = len(dataInfo[dataInfo["room_type"] == "Private room"])
sharedTotal = len(dataInfo[dataInfo["room_type"] == "Shared room"])
priv = (privateTotal / roomTotal) * 100
shared = (sharedTotal / roomTotal) * 100
privateTotalInfo = f"Rooms that are private: {priv}%"
print(privateTotalInfo)
publicTotalInfo = f"Rooms that are shared: {shared}%"
print(publicTotalInfo)

Rooms that are private: 45.444580566122895%
Rooms that are shared: 2.12134889419047%

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [ ]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
dataInfo.groupby("neighbourhood_group").size()

In [ ]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
dataInfo.groupby("neighbourhood_group")["price"].mean()

In [ ]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
dataInfo.groupby("room_type")["price"].mean()

In [ ]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
dataInfo.groupby("neighbourhood_group")["price"].agg(["min", "max"])
#.agg() method used to apply one or more mathematical operations across data axes

In [ ]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
dataInfo.groupby(["room_type", "neighbourhood_group"])["price"].mean()

In [ ]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
dataInfo.groupby(["room_type", "neighbourhood_group"])["price"].agg(["count", "min", "max", "mean", "median", "std"])

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [16]:
# 1. Load the `prices.csv` and the `n_listings.csv`
prices = pd.read_csv("../data/prices.csv")
n_listings = pd.read_csv("../data/n_listings.csv", sep=";")

In [17]:
# 2. Do join that keeps all the records for each table.
joined_csv = pd.merge(prices, n_listings, on="neighbourhood_group", how="outer")

In [18]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
joined_csv.to_csv("joined.csv")

In [19]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
pd.read_csv("joined.csv")

   Unnamed: 0 neighbourhood_group   mean_price  n_listings
0           0               Bronx    92.751479      1183.0
1           1            Brooklyn   120.225258     18632.0
2           2          LongIsland          NaN      4121.0
3           3           Manhattan   191.880466     20580.0
4           4              Queens    99.754965         NaN
5           5       Staten Island   110.947214         NaN

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.